language: php

php:
 - 5.4
 - 5.5
 - 5.6
 - hhvm
 - hhvm-nightly

before_script:
 - ./.travis.install.sh

script:
 - ./vendor/bin/phpunit --configuration=phpunit.travis.xml

matrix:
 allow_failures:
  - php: 5.3.3

addons:
 code_climate:
  repo_token: 378324e6f58cac254441ca887e602c782456c7304d0e6c957487cae2e380a8da

after_script:
 - ./vendor/bin/test-reporter
